all:
  hosts:
    node1:
      ansible_host: ''
      ip: 10.0.0.9
      access_ip: 'k8s-cluster.southeastasia.cloudapp.azure.com'
    node2:
      ansible_host: 10.0.0.5
      ip: 10.0.0.5
      access_ip: 10.0.0.5
    node3:
      ansible_host: 10.0.0.6
      ip: 10.0.0.6
      access_ip: 10.0.0.6
    node4:
      ansible_host: 10.0.0.7
      ip: 10.0.0.7
      access_ip: 10.0.0.7
    node5:
      ansible_host: 10.0.0.8
      ip: 10.0.0.8
      access_ip: 10.0.0.8
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
